### ISSUE TITLE
Unable to load preferences 

### ISSUE THREAD

**Issue by MadRater** [xyaman/cucu#1]
I am uncover 6.2.0. The settings page shows this.
![C9298740-CC51-4EEC-81C3-E9EC4F38EBD2](https://user-images.githubusercontent.com/81596201/129011982-20535287-a2bb-49ea-ab6f-0d4cd33cbade.png)

**Comment by xyaman** [comment]
what ios version?

**Comment by MadRater** [comment]
iOS 14.3

**Comment by xyaman** [comment]
You can try to remove cucu preferences bundle file and reinstall.

**Comment by xyaman** [comment]
Do you still have this problem?

**Comment by MadRater** [comment]
I fixed it actually by going into the directory it said and renaming I want
to say cucu-ios14 to cucu. It was a naming issue for me. After that the
preferences loaded fine. It was looking for an image file that wasn’t
there.

**Comment by xyaman** [comment]
Great!
